// console.log(myDate.toDateString())
// console.log(myDate.toISOString())
// console.log(myDate.toJSON())
// console.log(myDate.toLocaleDateString('en-IN'))
// console.log(myDate.toLocaleString())
// console.log(myDate.toString())
// let timeRegistered = Date.now()
// // console.log(timeRegistered)
// // console.log(myDate.getTime())
// console.log(Date.now().toString())
let myDate = new Date()
console.log(myDate.toLocaleString('en-IN'))
console.log(myDate.getFullYear())
console.log(myDate.getDate())
console.log(myDate.toDateString())
console.log(myDate.getMonth())
console.log(myDate.getTimezoneOffset())


